Add first frame
Megumin2k17/andrey_css_test_01_09_2023 pull request #1
Opened 2023-09-03 14:13 UTC by Megumin2k17

2023-09-03 15:12 UTC, andrey-kudinov requested changes
в целом круто всё сделал

посмотри пожалуйста комментари и добавь пожалуйста адаптив
я уверен что здесь это будет сделать очень просто)

2023-09-03 15:12 UTC, andrey-kudinov commented on style_01.css
> +}
респект что разобрался со шрифтами

2023-09-03 15:12 UTC, andrey-kudinov commented on style_01.css
> +#frame01 {
используй пожалуйста БЭМ для изоляции стилей
я работаю в австралийской конторе и с удивлением увидел что даже австралийцы юзают БЭМ

для изоляции стилей есть и более современные подходы но считаю что БЭМ тоже нужно знать
тем более в СНГ

2023-09-03 15:12 UTC, andrey-kudinov commented on style_01.css
> +	color: var(--black-whites-110-c-11, #110c11);
а где ты эту переменную задаёшь, подскажи пожалуйста?

2023-09-03 15:12 UTC, andrey-kudinov commented on style_01.css
> +	font-weight: 400;
такой стиль и вес дефолтный, не обязательно прописывать отдельно

2023-09-03 15:12 UTC, andrey-kudinov commented on style_01.css
> +#frame01 .solution > h3 {
такая система изоляции стилей на более крупном проекте вызовет путаницу и сложности  с поддержкой

будет сложно перебить стили из-за разной специфичности

2023-09-03 15:12 UTC, andrey-kudinov commented on style_01.css
> +	width: calc(100% / 3 - 36px);
обычно такие не совсем оччвидные числа как 36 выносят в отдельную переменную прямо внутри свойства чтобы из её названия было понятно что именно за 36

2023-09-03 15:16 UTC, Megumin2k17 commented on style_01.css
> +	color: var(--black-whites-110-c-11, #110c11);
Ой, это я скопипастил из фигмы и не отредактировал.

2023-09-03 18:05 UTC, andrey-kudinov commented on index.html
> +		<div id="frame01">
я думаю тег section подойдёт

2023-09-03 18:06 UTC, andrey-kudinov commented on index.html
> +		<div id="frame01">
класс `solutions` например

2023-09-03 18:06 UTC, andrey-kudinov commented on index.html
> +			<div class="page-title">
`solutions__title-container`

2023-09-03 18:07 UTC, andrey-kudinov commented on index.html
> +			<div class="cards-container">
`solutions__cards`

2023-09-03 18:07 UTC, andrey-kudinov commented on index.html
> +				<div class="cards-container__card">
`solutions__card`

2023-09-03 18:08 UTC, andrey-kudinov commented on index.html
> +					<h3 class="cards-container__card__title">ui/ux development</h3>
нет, так не надо
многосоставной БЭМ юзается на оч сложных и больших блоках
у нас и близко такого нет
всегда блок__элемент или блок__элемент--модификатор

2023-09-03 18:08 UTC, andrey-kudinov commented on index.html
> +					<h3 class="cards-container__card__title">ui/ux development</h3>
`solutions__carrd-title`

2023-09-03 18:08 UTC, andrey-kudinov commented on index.html
> +					<p class="cards-container__card__text">
`solutions__card-text`

2023-09-04 16:19 UTC, andrey-kudinov commented on index.html
> +			<div class="solutions">
такой класс всегда родительский
класс `solutions` тогда у секции
а здесь `solutions__cards`

2023-09-04 16:20 UTC, andrey-kudinov commented on style_01.css
> +}
тебе не нужно её на корне делать

2023-09-04 16:21 UTC, andrey-kudinov commented on style_01.css
> +.solutions__card {
```
.solutions__card {
    --solutions-gap: 10px; // вот так например более предпочтительно чтобы не засорять глобальную область видимости
	width: calc(100% / 3 - var(--solutions-gap));
	display: inline-flex;
	padding: 22px;
	flex-direction: column;
	align-items: flex-start;
	gap: 28px;
	background-color: white;
}
```

2023-09-04 16:22 UTC, andrey-kudinov commented on style_01.css
> +	gap: 36px;
или объявить её здесь и здесь же и заюзать
чтобы дважды одни и теже параметры не менять при адаптивности

2023-09-04 16:53 UTC, merged